### ISSUE TITLE
s3TogglzConfig and mongoTogglzConfig can exist at the same time

### ISSUE THREAD

**Issue by ewoelfel** [otto-de/edison-microservice#261]
Since release 2.4.7 it is possible to accidentally have a mongo togglz repo instead of s3 even though the config is looking like this 
```
edison:
  togglz:
    s3:
      enabled: true
      bucket-name:someBucket
```
This is possible when a MongoClient is used in the service because of this matchIfMissing:

```
@ConditionalOnProperty(prefix = "edison.togglz", name = "mongo.enabled", havingValue = "true", matchIfMissing = true)
```

It would be better if the application would fail fast, if both configs are possible
